version: '3.3'

services:
  java_db:
    image: postgres:12
    container_name: java_db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: product
      POSTGRES_USER: product_user
      POSTGRES_PASSWORD: EPQ4xbRrgA*zwd

  app:
    build: .
    container_name: spring-app
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: jdbc:postgresql://java_db:5432/product
      DATABASE_USERNAME: product_user
      DATABASE_PASSWORD: EPQ4xbRrgA*zwd
    depends_on:
      - java_db