spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgresPlusDialect
    show-sql: false
  flyway:
    out-of-order: true
    locations:
      - classpath:db/migration/
    enabled: true

springdoc:
  swagger-ui:
    operationsSorter: method
    tagsSorter: alpha
    filter: true
    tryItOutEnabled: true
  
  packages-to-scan: com.backend.api.infrastructure.controller

security:
  jwt:
    secret-key: ${JWT_SECRET:3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b}
    expiration-time: ${JWT_EXPIRATION:3600000}